import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    features: 'Features',
    leaderboard: 'Leaderboard',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    github: 'GitHub',
    startCoding: 'Start Coding',
    learnMore: 'Learn More',
    heroOverline: 'AI-POWERED C LEARNING',
    heroTitle: 'Visualize the <span className="text-emerald">Memory</span> of Your Code',
    heroSub: 'The deep-space command terminal for learning C. Track pointers, stack frames, and heap allocations in real-time with surgical precision.',
    launchWorkspace: 'Launch Workspace',
    liveHeapMap: 'LIVE HEAP MAP',
    active: 'ACTIVE',
    coreFeatures: 'Core Features',
    cVisualizer3ways: 'C언어를 <span className="text-accent">시각화</span>하는 3가지 방법',
    coreFeaturesDesc: '기획서에 담긴 세 가지 핵심 기능으로 추상적인 C언어를 직관적으로 이해합니다.',
    liveMemoryVisualizer: 'Live Memory Visualizer',
    liveMemoryVisualizerDesc: '코드의 각 줄이 실행될 때 Stack / Heap / Data 세그먼트가 실시간으로 어떻게 변하는지 시각화합니다. 포인터가 가리키는 주소, 변수의 생명주기를 한눈에 확인하세요.',
    stepByStepExecution: '단계별 실행 흐름 시각화',
    stepByStepExecutionDesc: '코드를 한 줄씩 실행하며 변수 변화와 제어 흐름을 직접 따라갑니다. 재생/일시정지로 원하는 속도에 맞춰 학습하세요.',
    humanReadableUI: 'Human-Readable UI/UX',
    humanReadableUIDesc: '에러 메시지를 한국어로 쉽게 설명하고, 수정 힌트까지 제공합니다. Segmentation Fault가 더 이상 무섭지 않아요.',
    stack: 'Stack',
    heap: 'Heap',
    dataSegment: 'Data 세그먼트',
    pointerTracking: '포인터 추적',
    stepByStep: 'Step-by-Step',
    variableTracking: '변수 추적',
    executionFlow: '실행 흐름',
    playbackControl: '재생 제어',
    koreanEnglishSupport: '한/영 지원',
    errorGuide: '에러 가이드',
    fixHint: '수정 힌트',
    intuitiveUI: '직관적 UI',
    empty: 'Empty',
    variableState: '변수 상태',
    fixHintLabel: '수정 힌트',
    segfaultDetected: 'Segmentation Fault',
    memoryLeakDetected: 'Memory Leak 감지',
    correctPointerUsage: '올바른 포인터 사용',
    ctaBadge: 'Draft · 2026.04.04',
    ctaTitle: '지금 바로<br /><span className="text-accent">C언어를 눈으로 확인</span>하세요',
    ctaSub: '포인터가 어떻게 동작하는지, 메모리가 어떻게 변하는지<br />코드 한 줄 한 줄 따라가며 직접 확인해보세요.',
    startFreeTrial: '무료로 체험 시작하기 →',
    noSignupRequired: '회원가입 없이 바로 사용 가능 · 한국어/영어 지원',
    product: 'Product',
    documentation: 'Documentation',
    social: 'Social',
    discord: 'Discord',
    twitter: 'X / Twitter',
    allRightsReserved: 'All rights reserved.',
    builtWith: 'Built with Emerald Signal',
    targetAudience: 'Target Audience',
    selfLearnerTitle: 'Self-Learner',
    studentTitle: 'Student Learning C',
    reviewerTitle: 'Those Who Want to Review',
    whyCVisualizer: 'Why C-Visualizer',
    problemsWithLearningC: '기존 C언어 학습의 <span className="text-accent">3가지 문제</span>',
    problemsDesc: '독학자와 학생들이 C언어에서 가장 많이 막히는 지점들입니다.',
    textOnlyProblem: '텍스트만으론 부족해요',
    textOnlyProblemDesc: '기존 C언어 교육은 설명과 코드 스니펫만으로 구성되어, 메모리가 실제로 어떻게 변하는지 눈으로 볼 수 없습니다.',
    pointerProblem: '포인터, 왜 이렇게 어렵죠?',
    pointerProblemDesc: '포인터, 스택, 힙 같은 추상적 개념을 머릿속으로만 상상해야 해서 입문자에게 높은 학습 장벽이 됩니다.',
    segfaultProblem: 'Segmentation Fault의 공포',
    segfaultProblemDesc: '오류가 어디서 왜 났는지 텍스트 메시지만으로 파악하기 어렵고, 디버깅 과정이 막막하게 느껴집니다.',
    whereDoesPointerPoint: 'Where does the pointer point?',
    welcome: 'Welcome',
    youAreLoggedIn: 'You are logged in.',
    goToIDE: 'Go to IDE',
    email: 'Email',
    nickname: 'Nickname',
    password: 'Password',
    yourDisplayName: 'Your display name',
    createAccount: 'Create Account',
    login: 'Login',
    logout: 'Logout',
    competition: 'COMPETITION',
    leaderboardTitle: 'Leaderboard',
    leaderboardSub: 'Top performers in C programming challenges.',
    loggedInAs: 'Logged in as',
    noParticipantsYet: 'No participants yet.',
    signUpToJoin: 'Sign up to join',
    rank: 'Rank',
    name: 'Name',
    solved: 'Solved',
    bestTime: 'Best Time',
    theme: 'Theme',
    runCode: 'Run Code',
    share: 'Share',
    problemInfo: 'PROBLEM INFO',
    problemList: 'PROBLEM LIST',
    terminal: 'TERMINAL',
    connectedToDebugger: 'Connected to Debugger',
    voltAgentEngine: 'VoltAgent Engine v1.0.4',
    noMemoryData: 'No memory data',
    noStackData: 'No stack data',
    noQueueData: 'No queue data',
    pricingTitle: 'Ready to master <span className="text-emerald">Memory</span>?',
    choosePlan: 'Choose the plan that fits your learning journey.',
    student: 'Student',
    studentPrice: '$0',
    studentDesc: 'Perfect for students starting their C journey.',
    proLearner: 'Pro Learner',
    proPrice: '$12',
    proDesc: 'Advanced features for serious developers.',
    university: 'University',
    uniPrice: '$49',
    uniDesc: 'For classrooms and learning groups.',
    mostPopular: 'MOST POPULAR',
    getStarted: 'Get Started',
    tryProFree: 'Try Pro Free',
    contactSales: 'Contact Sales',
    waitingForExecution: 'Waiting for execution...',
    success: 'Success! Problem solved.',
    errorOutputMismatch: 'Error: Output does not match expected',
    errorSumIncorrect: 'Error: Sum not printed correctly.',
    errorIncorrectLogic: 'Error: Incorrect logic or output.',
    tryPushing: 'Try pushing 10, 20, and 30 to the stack.',
    tryEnqueuing: 'Try enqueuing 1, 2, and 3 to the queue.',
    compilationFailed: 'Compilation failed.',
    curriculum: 'Curriculum',
    curriculumDesc: 'C Programming Complete Guide',
    chapter1: '1. Basic Syntax',
    chapter1Desc: 'Introduction to C and environment setup',
    chapter1Topics: 'Basic syntax and data types, Standard I/O (printf, scanf), Variables and constants, Operators (arithmetic, relational, logical)',
    chapter2: '2. Control Flow',
    chapter2Desc: 'Controlling program execution',
    chapter2Topics: 'Conditionals (if, else, switch), Loops (for, while, do-while), Control statements (break, continue, goto)',
    chapter3: '3. Functions & Memory',
    chapter3Desc: 'Function definitions and memory management',
    chapter3Topics: 'Function definition and calling, Recursion, Variable scope (local, global, static)',
    chapter4: '4. Basic Data Structures',
    chapter4Desc: 'Arrays and pointers fundamentals',
    chapter4Topics: 'Arrays (1D, multidimensional), Pointers (concepts, address operations), Pointer-array relationship, Pointers and functions (Call by Value/Reference)',
    chapter5: '5. User-Defined Types',
    chapter5Desc: 'Creating custom data types',
    chapter5Topics: 'Structures (struct), Unions (union) and enums, Dynamic memory allocation (malloc, free)',
    chapter6: '6. Advanced Data Management',
    chapter6Desc: 'File I/O and advanced concepts',
    chapter6Topics: 'File input/output, Preprocessor and macros, Linked List basics',
    chapter7: '7. Advanced Problems',
    chapter7Desc: 'Practical Skills',
    chapter7Topics: 'Doubly linked list, Stack calculator, Sorting algorithms (Bubble/Quick), Hash table, Binary tree, Memory pool',
    p1Title: '1. Hello World',
    p1Desc: 'Print "Hello, World!" to the console using printf().',
    p2Title: '2. Variable Sum',
    p2Desc: 'Declare two integers and print their sum.',
    p3Title: '3. Operators',
    p3Desc: 'Practice arithmetic operators: +, -, *, /, %',
    p4Title: '4. Even or Odd',
    p4Desc: 'Use if-else to check if a number is even or odd.',
    p5Title: '5. Days of Week',
    p5Desc: 'Use switch-case to print day names.',
    p6Title: '6. For Loop',
    p6Desc: 'Print numbers 1 to 10 using a for loop.',
    p7Title: '7. While Loop',
    p7Desc: 'Print numbers using a while loop.',
    p8Title: '8. Function',
    p8Desc: 'Create a function that returns the square of a number.',
    p9Title: '9. Recursion',
    p9Desc: 'Calculate factorial using recursion.',
    p10Title: '10. Array Basics',
    p10Desc: 'Store and print elements in an array.',
    p11Title: '11. Pointer Basics',
    p11Desc: 'Learn pointer basics: address and dereference.',
    p12Title: '12. Pointer Arithmetic',
    p12Desc: 'Use pointer arithmetic to traverse an array.',
    p13Title: '13. Struct',
    p13Desc: 'Define and use a structure (struct).',
    p14Title: '14. Dynamic Memory',
    p14Desc: 'Allocate memory with malloc() and free().',
    p15Title: '15. Linked List',
    p15Desc: 'Create and traverse a linked list.',
    p16Title: '16. File I/O',
    p16Desc: 'Write to and read from a file.',
    curriculumAdvanced: 'Advanced Problems',
    p17Title: '17. Doubly Linked List',
    p17Desc: 'Implement a doubly linked list and traverse from front and back.',
    p18Title: '18. Stack Calculator',
    p18Desc: 'Use a stack to convert infix to postfix notation and evaluate.',
    p19Title: '19. Bubble Sort',
    p19Desc: 'Sort an array in ascending order using bubble sort.',
    p20Title: '20. Quick Sort',
    p20Desc: 'Sort an array using quick sort.',
    p21Title: '21. Memory Pool',
    p21Desc: 'Implement your own malloc and free to create a memory pool.',
    p22Title: '22. Hash Table',
    p22Desc: 'Implement a hash table using chaining.',
    p23Title: '23. Recursive File Search',
    p23Desc: 'Use recursion to traverse all files in a directory.',
    p24Title: '24. Binary Tree',
    p24Desc: 'Implement a binary tree and do preorder, inorder, postorder traversal.',
  },
  ko: {
    features: '기능',
    leaderboard: '리더보드',
    signIn: '로그인',
    signUp: '회원가입',
    github: '깃허브',
    getStarted: '시작하기',
    startCoding: '코딩 시작',
    learnMore: '자세히 보기',
    heroOverline: 'AI 기반 C 언어 학습',
    heroTitle: '코드의 <span className="text-emerald">메모리</span>를 시각화하세요',
    heroSub: 'C 언어를 학습하기 위한 딥스페이스 명령 터미널. 포인터, 스택 프레임, 힙 할당을 실시간으로 정밀하게 추적하세요.',
    launchWorkspace: '워크스페이스 실행',
    liveHeapMap: '라이브 힙 맵',
    active: '활성',
    coreFeatures: '핵심 기능',
    cVisualizer3ways: 'C언어를 <span className="text-accent">시각화</span>하는 3가지 방법',
    coreFeaturesDesc: '기획서에 담긴 세 가지 핵심 기능으로 추상적인 C언어를 직관적으로 이해합니다.',
    liveMemoryVisualizer: '라이브 메모리 시각화',
    liveMemoryVisualizerDesc: '코드의 각 줄이 실행될 때 Stack / Heap / Data 세그먼트가 실시간으로 어떻게 변하는지 시각화합니다. 포인터가 가리키는 주소, 변수의 생명주기를 한눈에 확인하세요.',
    stepByStepExecution: '단계별 실행 흐름 시각화',
    stepByStepExecutionDesc: '코드를 한 줄씩 실행하며 변수 변화와 제어 흐름을 직접 따라갑니다. 재생/일시정지로 원하는 속도에 맞춰 학습하세요.',
    humanReadableUI: '직관적 UI/UX',
    humanReadableUIDesc: '에러 메시지를 한국어로 쉽게 설명하고, 수정 힌트까지 제공합니다. Segmentation Fault가 더 이상 무섭지 않아요.',
    stack: '스택',
    heap: '힙',
    dataSegment: '데이터 세그먼트',
    pointerTracking: '포인터 추적',
    stepByStep: '단계별',
    variableTracking: '변수 추적',
    executionFlow: '실행 흐름',
    playbackControl: '재생 제어',
    koreanEnglishSupport: '한/영 지원',
    errorGuide: '에러 가이드',
    fixHint: '수정 힌트',
    intuitiveUI: '직관적 UI',
    empty: '비어있음',
    variableState: '변수 상태',
    fixHintLabel: '수정 힌트',
    segfaultDetected: '세그멘테이션 폴트',
    memoryLeakDetected: '메모리 누수 감지',
    correctPointerUsage: '올바른 포인터 사용',
    ctaBadge: '기획 초안 · 2026.04.04',
    ctaTitle: '지금 바로<br /><span className="text-accent">C언어를 눈으로 확인</span>하세요',
    ctaSub: '포인터가 어떻게 동작하는지, 메모리가 어떻게 변하는지<br />코드 한 줄 한 줄 따라가며 직접 확인해보세요.',
    startFreeTrial: '무료로 체험 시작하기 →',
    noSignupRequired: '회원가입 없이 바로 사용 가능 · 한국어/영어 지원',
    product: '제품',
    documentation: '문서',
    social: '소셜',
    discord: '디스코드',
    twitter: 'X / 트위터',
    allRightsReserved: 'All rights reserved.',
    builtWith: 'Built with Emerald Signal',
    targetAudience: '타겟 대상',
    forSelfLearners: '이런 분들을 위해 <span className="text-accent">만들었습니다</span>',
    forAllLearners: '독학자와 학생 모두가 막히는 지점 없이 C언어를 이해할 수 있도록 설계했습니다.',
    selfLearnerTitle: '혼자 공부하는 독학자',
    selfLearnerDesc: '강의나 책만으로 C언어를 배우는 독학자. 막히는 개념을 스스로 해결할 수 있도록 시각적 단서와 직관적인 설명을 제공합니다.',
    studentTitle: 'C언어를 배우는 학생',
    studentDesc: '수업에서 C언어를 처음 접하는 학생. 교수님 설명만으로 이해하기 어려운 메모리 구조와 실행 흐름을 시각적으로 확인하세요.',
    reviewerTitle: '개념을 다시 잡고 싶은 분',
    reviewerDesc: 'C언어를 배웠지만 내부 원리가 여전히 모호한 분. 시각화를 통해 놓쳤던 개념을 빠르게 정리하세요.',
    selfLearning: '자기주도 학습',
    conquerPointers: '포인터 극복',
    buildFoundation: '기초 다지기',
    classSupplement: '수업 보조',
    homeworkHelp: '과제 도움',
    examPrep: '시험 대비',
    review: '복습',
    memoryStructure: '메모리 구조',
    debuggingSkill: '디버깅 실력',
    whyCVisualizer: '왜 C-Visualizer인가',
    problemsWithLearningC: '기존 C언어 학습의 <span className="text-accent">3가지 문제</span>',
    problemsDesc: '독학자와 학생들이 C언어에서 가장 많이 막히는 지점들입니다.',
    textOnlyProblem: '텍스트만으론 부족해요',
    textOnlyProblemDesc: '기존 C언어 교육은 설명과 코드 스니펫만으로 구성되어, 메모리가 실제로 어떻게 변하는지 눈으로 볼 수 없습니다.',
    pointerProblem: '포인터, 왜 이렇게 어렵죠?',
    pointerProblemDesc: '포인터, 스택, 힙 같은 추상적 개념을 머릿속으로만 상상해야 해서 입문자에게 높은 학습 장벽이 됩니다.',
    segfaultProblem: 'Segmentation Fault의 공포',
    segfaultProblemDesc: '오류가 어디서 왜 났는지 텍스트 메시지만으로 파악하기 어렵고, 디버깅 과정이 막막하게 느껴집니다.',
    whereDoesPointerPoint: '포인터가 어딜 가리키나요?',
    welcome: '환영합니다',
    youAreLoggedIn: '로그인되었습니다.',
    goToIDE: 'IDE로 이동',
    email: '이메일',
    nickname: '닉네임',
    password: '비밀번호',
    yourDisplayName: '표시할 이름',
    createAccount: '계정 만들기',
    login: '로그인',
    logout: '로그아웃',
    competition: '경쟁',
    leaderboardTitle: '리더보드',
    leaderboardSub: 'C 프로그래밍 챌린지의 최우수 학생들.',
    loggedInAs: '로그인됨:',
    noParticipantsYet: '아직 참가자가 없습니다.',
    signUpToJoin: '가입하여 참여하기',
    rank: '순위',
    name: '이름',
    solved: '푼 문제',
    bestTime: '최고 시간',
    theme: '테마',
    runCode: '코드 실행',
    share: '공유',
    problemInfo: '문제 정보',
    problemList: '문제 목록',
    terminal: '터미널',
    connectedToDebugger: '디버거에 연결됨',
    voltAgentEngine: 'VoltAgent 엔진 v1.0.4',
    noMemoryData: '메모리 데이터 없음',
    noStackData: '스택 데이터 없음',
    noQueueData: '큐 데이터 없음',
    pricingTitle: '<span className="text-emerald">메모리</span> 마스터할 준비가 되셨나요?',
    choosePlan: '학습 여정에 맞는 플랜을 선택하세요.',
    student: '학생',
    studentPrice: '₩0',
    proLearner: '프로 학습자',
    proPrice: '₩15,000',
    proDesc: '진지한 개발자를 위한 고급 기능.',
    university: '대학교',
    uniPrice: '₩60,000',
    uniDesc: '교실 및 학습 그룹용.',
    mostPopular: '가장 인기',
    tryProFree: '프로 무료 체험',
    contactSales: '영업 문의',
    waitingForExecution: '실행 대기 중...',
    success: '성공! 문제를 해결했습니다.',
    errorOutputMismatch: '오류: 출력이 예상과 일치하지 않습니다',
    errorSumIncorrect: '오류: 합이 올바르게 출력되지 않았습니다.',
    errorIncorrectLogic: '오류: 논리가 올바르지 않거나 출력이 잘못되었습니다.',
    tryPushing: '10, 20, 30을 스택에 푸시해보세요.',
    tryEnqueuing: '1, 2, 3을 큐에 넣어보세요.',
    compilationFailed: '컴파일 실패.',
    problem1Title: '1. Hello World',
    problem1Desc: 'printf를 사용하여 "Hello, World!"를 콘솔에 출력하세요.',
    problem2Title: '2. 변수 합',
    problem2Desc: '두 정수 a와 b를 선언하고 10과 20을 할당한 후 그 합을 출력하세요.',
    problem3Title: '3. 스택 푸시',
    problem3Desc: '간단한 스택을 구현하고 값 10, 20, 30을 스택에 푸시하세요.',
    problem4Title: '4. 큐 인큐',
    problem4Desc: '간단한 큐를 구현하고 값 1, 2, 3을 큐에 인큐하세요.',
    curriculum: '커리큘럼',
    curriculumDesc: 'C 프로그래밍 완벽 가이드',
    chapter1: '1. 기초 문법',
    chapter1Desc: 'C언어 소개 및 환경 설정',
    chapter1Topics: '기본 문법 및 데이터 타입, 표준 입출력 함수 (printf, scanf), 변수와 상수, 연산자 (산술, 관계, 논리)',
    chapter2: '2. 제어 흐름',
    chapter2Desc: '프로그램 실행 흐름 제어',
    chapter2Topics: '조건문 (if, else, switch), 반복문 (for, while, do-while), 제어문 (break, continue, goto)',
    chapter3: '3. 함수와 메모리',
    chapter3Desc: '함수의 정의와 메모리 관리',
    chapter3Topics: '함수의 정의와 호출, 재귀 함수 (Recursion), 변수의 범위 (지역, 전역, 정적 변수)',
    chapter4: '4. 데이터 구조 기초',
    chapter4Desc: '배열과 포인터 기초',
    chapter4Topics: '배열 (1차원, 다차원), 포인터 (개념, 주소 연산), 포인터와 배열의 관계, 포인터와 함수 (Call by Value/Reference)',
    chapter5: '5. 사용자 정의 자료형',
    chapter5Desc: '사용자 정의 데이터 타입 만들기',
    chapter5Topics: '구조체 (struct), 공용체 (union) 및 열거형 (enum), 동적 메모리 할당 (malloc, free)',
    chapter6: '6. 고급 데이터 관리',
    chapter6Desc: '파일 입출력 및 고급 개념',
    chapter6Topics: '파일 입출력, 전처리기 및 매크로, 연결 리스트 (Linked List) 기초',
    chapter7: '7. 심화 문제',
    chapter7Desc: '실전 능력 향상',
    chapter7Topics: '이중 연결 리스트, 스택 계산기, 정렬 알고리즘 (버블/퀵), 해시 테이블, 이진 트리, 메모리 풀',
    p1Title: '1. Hello World',
    p1Desc: 'printf()를 사용하여 "Hello, World!"를 콘솔에 출력하세요.',
    p2Title: '2. 변수 합',
    p2Desc: '두 정수를 선언하고 그 합을 출력하세요.',
    p3Title: '3. 연산자',
    p3Desc: '산술 연산자 +, -, *, /, % 연습하기',
    p4Title: '4. 짝수와 홀수',
    p4Desc: 'if-else를 사용하여 수가 짝수인지 홀수인지 판별하세요.',
    p5Title: '5. 요일',
    p5Desc: 'switch-case를 사용하여 요일 이름을 출력하세요.',
    p6Title: '6. For 반복문',
    p6Desc: 'for 반복문을 사용하여 1부터 10까지 출력하세요.',
    p7Title: '7. While 반복문',
    p7Desc: 'while 반복문을 사용하여 숫자를 출력하세요.',
    p8Title: '8. 함수',
    p8Desc: '숫자의 제곱을 반환하는 함수를 만드세요.',
    p9Title: '9. 재귀',
    p9Desc: '재귀를 사용하여 팩토리얼을 계산하세요.',
    p10Title: '10. 배열 기초',
    p10Desc: '배열에 요소를 저장하고 출력하세요.',
    p11Title: '11. 포인터 기초',
    p11Desc: '포인터 기초: 주소와 역참조 배우기',
    p12Title: '12. 포인터 연산',
    p12Desc: '포인터 연산을 사용하여 배열을 탐색하세요.',
    p13Title: '13. 구조체',
    p13Desc: '구조체(struct)를 정의하고 사용하세요.',
    p14Title: '14. 동적 메모리',
    p14Desc: 'malloc()으로 메모리를 할당하고 free()로 해제하세요.',
    p15Title: '15. 연결 리스트',
    p15Desc: '연결 리스트를 생성하고 탐색하세요.',
    p16Title: '16. 파일 입출력',
    p16Desc: '파일에 쓰기하고 읽어오세요.',
    curriculumAdvanced: '심화 문제',
    p17Title: '17. 이중 연결 리스트',
    p17Desc: '이중 연결 리스트를 구현하고 앞에서부터, 뒤에서부터 탐색하세요.',
    p18Title: '18. 스택 계산기',
    p18Desc: '스택을 사용하여 중위 표기법을 후위 표기법으로 변환하고 계산하세요.',
    p19Title: '19. 버블 정렬',
    p19Desc: '배열을 버블 정렬로 오름차순 정렬하세요.',
    p20Title: '20. 퀵 정렬',
    p20Desc: '배열을 퀵 정렬로 정렬하세요.',
    p21Title: '21. 메모리 풀',
    p21Desc: 'malloc과 free를 직접 구현하여 메모리 풀을 만드세요.',
    p22Title: '22. 해시 테이블',
    p22Desc: '체이닝 방식을 사용하여 해시 테이블을 구현하세요.',
    p23Title: '23. 재귀 파일 탐색',
    p23Desc: '재귀를 사용하여 디렉토리 내 모든 파일을 탐색하세요.',
    p24Title: '24. 이진 트리',
    p24Desc: '이진 트리를 구현하고 전위, 중위, 후위 순회하세요.',
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}